name: 📜 Auto-Generate Release Notes

# trigger on "Create release" in the GitHub UI or via API
on:
  release:
    types: [created]

# give yourself explicit read permissions so the runner can fetch actions
permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) pull down your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) pick up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) install the published package
      - name: Install changelog-weaver
        run: |
          python -m pip install --upgrade pip
          pip install changelog-weaver

      # 4) generate a .env from GitHub vars
      - name: Write .env
        run: |
          cat <<EOF >.env
          SOLUTION_NAME=${{ github.repository }}
          RELEASE_VERSION=${{ github.ref_name }}
          SOFTWARE_SUMMARY=Release ${{ github.ref_name }}
          GET_ITEM_SUMMARY=True
          GET_CHANGELOG_SUMMARY=True
          PROJECT_URL=https://github.com/${{ github.repository }}
          QUERY=is:closed
          ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}
          GPT_API_KEY=${{ secrets.GPT_API_KEY }}
          MODEL_BASE_URL=https://api.openai.com/v1
          MODEL=gpt-4o-mini
          OUTPUT_FOLDER=Releases
          LOG_LEVEL=INFO
          EOF

      # 5) actually generate your markdown files
      - name: Generate Changelog
        run: python -m changelog_weaver
      - name: List Generated Files
        run: ls -R Releases
      # 6) upload as a artifacts for inspection
      - name: Upload Changelog artifact
        uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: Releases/*.md

      # 7) attach it to the same release you just created
      - name: Attach to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: Releases/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
