name: 📜 Auto-Generate Release Notes

on:
  release:
    types: [created]

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install changelog-weaver
        run: |
          python -m pip install --upgrade pip
          pip install changelog-weaver

      - name: Write .env
        run: |
          cat <<EOF >.env
          SOLUTION_NAME=${{ github.repository }}
          RELEASE_VERSION=${{ github.ref_name }}
          SOFTWARE_SUMMARY=Release ${{ github.ref_name }}
          GET_ITEM_SUMMARY=True
          GET_CHANGELOG_SUMMARY=True
          PROJECT_URL=https://github.com/${{ github.repository }}
          QUERY=is:closed
          ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}
          GPT_API_KEY=${{ secrets.GPT_API_KEY }}
          MODEL_BASE_URL=https://api.openai.com/v1
          MODEL=gpt-4o-mini
          OUTPUT_FOLDER=Releases
          LOG_LEVEL=INFO
          EOF

      - name: Generate Changelog
        run: python -m changelog_weaver

      - name: Upload Changelog artifact
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: Releases/*.md

      - name: Attach to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: Releases/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
